id: I828F6807
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-01T12:35:06+00:00'
last_modified: '2022-06-13T12:44:53.330135+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS105195
  title: ཐོབ་ཡིག་བུམ་པ་བཟང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6162':
      image_group_id: I1PD36271
      title: ''
      total_pages: ''
      order: 1
      base_file: 6162.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
